linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 140

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
  disable:
    - typecheck  # Often causes issues with mocks

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false
